FROM node:20 AS builder

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install --only=production

COPY . ./
RUN npm install typescript --save-dev
RUN npm run build


FROM nginx:alpine


RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /usr/src/app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]